### ISSUE TITLE
Download particular devations

### ISSUE THREAD

**Issue by Qwerty-Space** [Galadirith/dadownloader#1]
Is this possible?  Instead of downloading the entire account

**Comment by Galadirith** [comment]
@Qwerty-Space Thank so much for the question. I think it is, but I have to be honest I have not worked on this project in over three years (as you can see from the last commit 😅 ).

I would actually recommend using DeviantArt's own API https://www.deviantart.com/developers/ which is much much more complete and so so much simpler than what I was doing with the project. And it's officially supported by DeviantArt where as this was at best a hack :smile:

I wrote about 60 lines of Python code earlier this year to basically do everything that this project was doing using their API. I see you have some Javascript experience, you could do exactly the same with Node.

I not sure how much experience you have with patterns like this, but please feel free to message back and let me know if I can help direct you at all :smile:

**Comment by Qwerty-Space** [comment]
It's okay, I use [RipMe](https://github.com/RipMeApp/ripme) now.
